name: Create Release

on:
  # release will only be created when ref is a tag starting with "v"
  push:
    tags:
      - "v*"
      
jobs:
  image:
    name: Create release and artifacts (release.yaml and GCR Container Image)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup ko
        # will install latest ko version and by default login/configure for ghcr.io
        uses: imjasonh/setup-ko@78eea08f10db87a7a23a666a4a6fe2734f2eeb8d

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get short COMMIT and TAG
        run: |
          echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
          echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV

      - name: Build and Publish Worker Image
        run: |
          # build, push and create release YAML
          ko resolve --tags ${KO_TAG},${KO_COMMIT},latest --bare -Rf config/ > release.yaml

      - name: Create Github Release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${KO_TAG} release.yaml README.md LICENSE
