name: Create Release

on:
  # release will only be created when ref is a tag starting with "v"
  push:
    tags:
      - "v*"
      
jobs:
  image:
    name: Create release and artifacts (release.yaml and GCR Container Image)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      KO_DOCKER_REPO: us.gcr.io/daisy-284300/veba/vsphere-event-stream

    steps:
      - name: Setup ko
        uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4 tag, will install latest ko version

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Get short COMMIT and TAG
        run: |
          echo "KO_COMMIT=$(echo -n $GITHUB_SHA | cut -c -8)" >> $GITHUB_ENV
          echo "KO_TAG=$(basename "${{ github.ref }}")" >> $GITHUB_ENV

      - name: Build and Publish Worker Image
        run: |
          # build, push and create release YAML
          ko resolve --tags ${KO_TAG},${KO_COMMIT},latest -BRf config/ > release.yaml
      
      - name: Create Github Release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${KO_TAG} release.yaml README.md LICENSE
